### ISSUE TITLE
初始化时无法获得binder

### ISSUE THREAD

**Issue by storytellerF** [RikkaApps/Shizuku-API#1]
`Shizuku.OnBinderReceivedListener` 事件接收不到，请求权限就会抛出异常，问题出现在`rikka.sui.Sui`的`IBinder received = reply.readStrongBinder();`，`received`是`null`。
步骤：

1. 添加依赖，添加`provider`，添加FreeReflection
2. 添加`Application`，调用`Sui.init(BuildConfig.APPLICATION_ID);`
3. `Activity` 绑定事件

**Comment by RikkaW** [comment]
Sui 是否正常安装
https://github.com/RikkaApps/Sui#guide-for-users 打开管理页面的方法有反应吗
https://github.com/RikkaApps/Riru/releases/download/v23.6/riru-v23.6.r279.f990471.apk 这里又说什么

**Comment by storytellerF** [comment]
@RikkaW 如果只用Shizuku是不是不需要调用`Sui.init(BuildConfig.APPLICATION_ID);`啊，那问题就只是`Shizuku.OnBinderReceivedListener` 事件接收不到，请求权限就会抛出异常。
步骤：

    添加依赖，添加`provider`，添加`FreeReflection`
    添加Application
    Activity 绑定事件

**Comment by RikkaW** [comment]
那么直接跑 demo 正常吗

**Comment by storytellerF** [comment]
没跑demo，我根据代码自己写的，所以我把步骤写上了，看看是不是哪里漏了什么

**Comment by RikkaW** [comment]
甚至在怀疑是不是 provider 没有加进 manifest（

**Comment by storytellerF** [comment]
添加了，内容一点没改，放到`<application>`里的，应该没有问题，我跑demo试试吧，看看demo能不能正常

**Comment by storytellerF** [comment]
demo运行完了，没有问题。
debug`ShizukuProvider`的`onCreate`，`attachInfo`都能捕获到，所以provider应该没有问题
我把`Shizuku-Api`的`api ``provider`等代码，直接整到我的项目，不用gradle处理，发现`call`函数没有被调用

**Comment by RikkaW** [comment]
让人怀疑是不是自己复制时这个丢了（
https://github.com/RikkaApps/Shizuku-API/blob/master/provider/src/main/AndroidManifest.xml#L6

**Comment by storytellerF** [comment]
我现在编译`Shizuku-API` 中的`api ` `provider ` `aidl`为aar引入项目，正常运行，能够接收到binder。
使用gradle 引入依赖的方式就不行

**Comment by RikkaW** [comment]
令人怀疑是不是在使用超古老的工具们

**Comment by lls2wow** [comment]
@RikkaW  你好作者 我demo运行正常, 环境是magisk+sui 13.5.1 .   但是代码挪到lsposed的插件代码中无法运行 Sui.init 报错java.lang.NoClassDefFoundError: Failed resolution of: Lrikka/sui/Sui; 因为是要注入别的程序 无法更改Anroid Manifest(重打包的话有签名校验) 是不是我没法使用这个API
