### ISSUE TITLE
为什么修改UserService中的代码，再次运行后还是上次的结果

### ISSUE THREAD

**Issue by Fearimdly** [RikkaApps/Shizuku-API#20]
我运行了demo，点击bindUserService，然后屏幕上输出了一串字符串。接着，我修改了UserService doSomething()方法， 在原本的字符串后面加上了一些内容，可是当我再次运行demo，点击bindUserService，得到的还是上次的结果。

**Comment by RikkaW** [comment]
![image](https://user-images.githubusercontent.com/12999176/195972628-d1869e5e-bf7a-4d4f-a174-cd692aaea741.png)
