### ISSUE TITLE
请问如何调用非SDK系统API

### ISSUE THREAD

**Issue by Moderpach** [RikkaApps/Shizuku-API#22]
我尝试以以下方式调用非SDK系统API，但是不起作用。
```
public static final Singleton<IPowerManager> POWER_MANAGER = new Singleton<IPowerManager>() {
        @Override
        protected IPowerManager create() {
            return IPowerManager.Stub.asInterface(new ShizukuBinderWrapper(SystemServiceHelper.getSystemService(Context.POWER_SERVICE)));
        }
    };
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {

  //这个不是隐藏api，可以访问到值
    HiddenApiBypass.invoke(IPowerManager::class.java, ShizukuSystemServerApi.POWER_MANAGER.get(), "isPowerSaveMode", true);
  //这个是隐藏api，调用后没有反应
    HiddenApiBypass.invoke(IPowerManager::class.java, ShizukuSystemServerApi.POWER_MANAGER.get(), "setPowerSaveModeEnabled", true);
}
```
请问如果我要调用PowerManager里的隐藏方法我应该如何操作呢？

**Comment by Moderpach** [comment]
如果使用`POWER_MANAGER.get().setPowerSaveModeEnabled(true);`
会运行时报错：
java.lang.NoSuchMethodError: No interface method setPowerSaveModeEnabled(Z)Z in class Landroid/os/IPowerManager; or its super classes (declaration of 'android.os.IPowerManager' appears in /system/framework/framework.jar!classes2.dex)

**Comment by xiangsss** [comment]
大佬， 这种是什么原因呢？

**Comment by Moderpach** [comment]
> 大佬， 这种是什么原因呢？

有 `@SystemApi` 注解的调不到

**Comment by xiangsss** [comment]
感谢解惑！ 还有个疑惑，是不是调用隐藏的api必须用 HiddenApiBypass.invoke ，不能直接用POWER_MANAGER.get().xxxx 这种方式？

**Comment by Moderpach** [comment]
不是，我个人觉得HiddenApiBypass不好用，我现在都用反射

**Comment by Moderpach** [comment]
不好意思，搞错了，调不调得到看这个https://developer.android.com/guide/app-compatibility/restrictions-non-sdk-interfaces

> > 大佬， 这种是什么原因呢？
> 
> 有 `@SystemApi` 注解的调不到
