### ISSUE TITLE
why Deprecated Shizuku.newProcess

### ISSUE THREAD

**Issue by iamr0s** [RikkaApps/Shizuku-API#29]
please don't deprecate the Shizuku.newProcess.

**Comment by iamr0s** [comment]
if I want execute some command by shizuku
in old api, I can use newProcess
in api 14, what method should I use?

**Comment by RikkaW** [comment]
UserService

**Comment by ysy950803** [comment]
> UserService, use can use it to run your Java and native codes with privilege.

So how to use UserService to implement and execute shell commands? I couldn't find any examples at all, please explain.
