### ISSUE TITLE
API Compatibility question

### ISSUE THREAD

**Issue by CasperVerswijvelt** [RikkaApps/Shizuku-API#33]
Hi

I can't seem to find any info about APP - API version compatibility other than the "preV11" check

Will the current version of the API (12.1.0) continue to work correctly with newer versions of Shizuku e.g. when shizuku 14 and shizuku-api 14 come out?  Is compatibility guaranteed until a specific version?

**Comment by RikkaW** [comment]
Yes, for sure, and we will do our best to maintain compatibility.
