### ISSUE TITLE
How to use app context in UserService?

### ISSUE THREAD

**Issue by nighthawkk** [RikkaApps/Shizuku-API#4]
from ApplicationUtils.getApplication() inside UserService, I'm getting null.
Anyone knows How to use app context in UserService?

**Comment by RikkaW** [comment]
There is no app context since UserService runs in a different process.
Your problem means you need to learn a lot about how things works behind.

**Comment by nighthawkk** [comment]
I know UserService runs in another process, and app context is not available there. That's why i am asking is there any workaround to use app context there.

**Comment by RikkaW** [comment]
'ActivityThread.systemMain().getSystemContext()'
'registerReceiver', content provider or any things that requires a valid ApplicationThread is not useable.

**Comment by nighthawkk** [comment]
okay.
