### ISSUE TITLE
如何通过Shizuku调用Shell

### ISSUE THREAD

**Issue by 250king** [RikkaApps/Shizuku-API#49]
因为项目需要，故要调用以下Shell：
/system/xbin/bstk/su
mount /system -o remount,rw
但看了半天开发文档还是摸不着头脑，故发个issue求解答

**Comment by RikkaW** [comment]
UserService 可以执行任意 Java 代码（支持 JNI），显然可以在里面自己运行一个 /system/bin/sh。

**Comment by 250king** [comment]
有没有Demo？

**Comment by RikkaW** [comment]
没有。这跟 Java 里执行指令一样的，只是不用自己再运行 su 提权了（当然如果 Shizuku 运行在 adb 下那就只有 adb）。
