### ISSUE TITLE
[bug] One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by lisonge** [RikkaApps/Shizuku-API#54]
<https://github.com/RikkaApps/Shizuku-API/blob/b26fcc841efcec90ae83a9de59ce590b8f298e75/provider/src/main/java/rikka/shizuku/ShizukuProvider.java#L121-L130>

<https://developer.android.com/about/versions/14/behavior-changes-14?hl=zh-cn#runtime-receivers-exported>

**Comment by Tithoword** [comment]
> https://github.com/RikkaApps/Shizuku-API/blob/b26fcc841efcec90ae83a9de59ce590b8f298e75/provider/src/main/java/rikka/shizuku/ShizukuProvider.java#L121-L130
> 
> [https://developer.android.com/about/versions/14/behavior-changes-14?hl=zh-cn#runtime-receivers-exported ](https://developer.android.com/about/versions/14/behavior-changes-14?hl=zh-cn#runtime-receivers-exported)

**Comment by tvruco** [comment]
> [Shizuku-API/provider/src/main/java/rikka/shizuku/ShizukuProvider.java](https://github.com/RikkaApps/Shizuku-API/blob/b26fcc841efcec90ae83a9de59ce590b8f298e75/provider/src/main/java/rikka/shizuku/ShizukuProvider.java#L121-L130)
> 
> Lines 121 to 130 in [b26fcc8](/RikkaApps/Shizuku-API/commit/b26fcc841efcec90ae83a9de59ce590b8f298e75)
> 
>  context.registerReceiver(new BroadcastReceiver() { 
>      @Override 
>      public void onReceive(Context context, Intent intent) { 
>          BinderContainer container = intent.getParcelableExtra(EXTRA_BINDER); 
>          if (container != null && container.binder != null) { 
>              Log.i(TAG, "binder received from broadcast"); 
>              Shizuku.onBinderReceived(container.binder, context.getPackageName()); 
>          } 
>      } 
>  }, new IntentFilter(ACTION_BINDER_RECEIVED)); 
> https://developer.android.com/about/versions/14/behavior-changes-14?hl=zh-cn#runtime-receivers-exported

**Comment by tvruco** [comment]
> > [Shizuku-API/provider/src/main/java/rikka/shizuku/ShizukuProvider.java](https://github.com/RikkaApps/Shizuku-API/blob/b26fcc841efcec90ae83a9de59ce590b8f298e75/provider/src/main/java/rikka/shizuku/ShizukuProvider.java#L121-L130)
> > Lines 121 to 130 in [b26fcc8](/RikkaApps/Shizuku-API/commit/b26fcc841efcec90ae83a9de59ce590b8f298e75)
> > context.registerReceiver(new BroadcastReceiver() {
> > [@OverRide](https://github.com/OverRide)
> > public void onReceive(Context context, Intent intent) {
> > BinderContainer container = intent.getParcelableExtra(EXTRA_BINDER);
> > if (container != null && container.binder != null) {
> > Log.i(TAG, "binder received from broadcast");
> > Shizuku.onBinderReceived(container.binder, context.getPackageName());
> > }
> > }
> > }, new IntentFilter(ACTION_BINDER_RECEIVED));
> > https://developer.android.com/about/versions/14/behavior-changes-14?hl=zh-cn#runtime-receivers-exported

- [ ] [``](url)

**Comment by tvruco** [comment]
> 

- [ ] 

> `[Shizuku-API/provider/src/main/java/rikka/shizuku/ShizukuProvider.java](https://github.com/RikkaApps/Shizuku-API/blob/b26fcc841efcec90ae83a9de59ce590b8f298e75/provider/src/main/java/rikka/shizuku/ShizukuProvider.java#L121-L130)`

> 
> Lines 121 to 130 in [b26fcc8](/RikkaApps/Shizuku-API/commit/b26fcc841efcec90ae83a9de59ce590b8f298e75)
> 
>  context.registerReceiver(new BroadcastReceiver() { 
>      @Override 
>      public void onReceive(Context context, Intent intent) { 
>          BinderContainer container = intent.getParcelableExtra(EXTRA_BINDER); 
>          if (container != null && container.binder != null) { 
>              Log.i(TAG, "binder received from broadcast"); 
>              Shizuku.onBinderReceived(container.binder, context.getPackageName()); 
>          } 
>      } 
>  }, new IntentFilter(ACTION_BINDER_RECEIVED)); 
> https://developer.android.com/about/versions/14/behavior-changes-14?hl=zh-cn#runtime-receivers-exported

Duplicate of #189 /

**Comment by lwanthusoe438-stack** [comment]
01e08879d58a5cb11a333535c6ddce9f7b7c88ff
