### ISSUE TITLE
没看懂demo，求大佬指点一下

### ISSUE THREAD

**Issue by fansangg** [RikkaApps/Shizuku-API#55]
我想在授权shizuku后执行shell命令，但是在demo没有翻到此类的操作，看了其他issue有提到，是需在service里执行命令吗？然后在bindservice后调用？

**Comment by Jesse205** [comment]
https://github.com/RikkaApps/Shizuku-API/issues/49

**Comment by zkywalker** [comment]
val process = Shizuku.newProcess(arrayOf("sh"), null, null)

**Comment by Jesse205** [comment]
> val process = Shizuku.newProcess(arrayOf("sh"), null, null)

这个方法在最新版本的依赖内已经变为了私有方法，且标为废弃，不推荐使用

**Comment by Jesse205** [comment]
https://gitee.com/ohos-dev/hap-viewer-android
我最近给hap查看器加入了hap安装功能，原理就是执行一句shell。实现的可能有一些不好，但是你可以参考一下。

**Comment by fansangg** [comment]
> https://gitee.com/ohos-dev/hap-viewer-android 我最近给hap查看器加入了hap安装功能，原理就是执行一句shell。实现的可能有一些不好，但是你可以参考一下。

感谢你的回答，看了你的代码，和我之前弄的时候实现是差不多的，但是我觉得这样在有些场景会显得麻烦一些

**Comment by Intro-iu** [comment]
同，没看懂，所以大佬们有什么执行shell的模板之类的吗
