### ISSUE TITLE
rish:use aidl-cpp to generate c++ binding to binder instead of rely on java

### ISSUE THREAD

**Issue by ccaapton** [RikkaApps/Shizuku-API#58]
Currently every call of rish will result in a dex process creation, which is very resources inefficient. Why not use c++ binding instead like described [here](https://stackoverflow.com/questions/65284392/aidl-interface-between-java-and-c)?

**Comment by RikkaW** [comment]
NDK Binder (the official public API) was added from API 29, and really becomes useable from API 30 if I remember correctly. I didn't choose NDK Binder at first considering compatibility.

`aidl-cpp` is an AOSP tool, so the generated code needs to be compiled with AOSP, and the final binary should link `libbinder` if I'm correct. Obviously, it's not guaranteed to work on all API versions / all systems.
