### ISSUE TITLE
is there an API check shizuku running?

### ISSUE THREAD

**Issue by vfishv** [RikkaApps/Shizuku-API#73]
is there an API check shizuku running or my app has no shizuku permission?

**Comment by negier** [comment]
I think you want method is Shizuku is prepared to execute our bingUserService code, not app is running.

**Comment by RikkaW** [comment]
There are BinderReceived/DeadListener in `rikka.shizuku.Shizuku` class, which tracks the state of existence of the `Binder` of Shizuku server. There is also `pingBinder` in Shizuku class which is directly. If this binder is dead, Shizuku server is not running.
Is the Shizuku app itself running does not matter.

Check permission: it's in README.
