### ISSUE TITLE
Request service to run as shell (when Shizuku has been started by root)

### ISSUE THREAD

**Issue by KieronQuinn** [RikkaApps/Shizuku-API#8]
This is a massive edge case, but I've found a scenario that it's needed. Not sure if it's a "bug" in the Manager or an API feature request, so I've put it here, but feel free to move it.

Basically, if you start Shizuku on a rooted device, subsequent calls to `getCallingUid()` (when not handling a transaction from the app) will return `0`, `root`. If the Shizuku service has been started by ADB, it will return `2000` (`com.android.shell`). This is expected, as the service has been started by those UIDs originally. 

However, there _are_ some cases (eg. the `launcherapps` and `shortcut` system services), where `root` is worse than `shell`, and the system service will actually reject calls from root, but take them from shell. Here's an example:

`ILauncherApps.aidl` (you'll also need to create the stubs for ParceledListSlice + its parent and ShortcutQueryWrapper, sorry - I can provide more if needed)
```aidl
package android.content.pm;

import android.os.UserHandle;
import android.content.pm.ParceledListSlice;
import android.content.pm.ShortcutQueryWrapper;

interface ILauncherApps {
    ParceledListSlice getShortcuts(String callingPackage, in ShortcutQueryWrapper query, in UserHandle user) = 13;
}
```

In a Shizuku service:

```kotlin
private val launcherApps by lazy {
    val launcherAppsProxy = SystemServiceHelper.getSystemService("launcherapps")
    ILauncherApps.Stub.asInterface(launcherAppsProxy)
}

//context is the system context, get it however you prefer
private fun getUserHandle(): UserHandle {
	return Context::class.java.getMethod("getUser").invoke(context) as UserHandle
}

override fun getShortcuts(query: ShortcutQueryWrapper) {
	val token = clearCallingIdentity()
	Log.d("TTSS", "getShortcuts ${getCallingUid()}")
	val shortcuts = launcherApps.getShortcuts("com.android.shell", query, getUserHandle()) as ParceledListSlice<ShortcutInfo>
	Log.d("TTSS", "Got shortcuts! Size ${shortcuts.list.size}")
	restoreCallingIdentity(token)
}
```

For the query you can use the generic:

```kotlin
val query = ShortcutQueryWrapper(LauncherApps.ShortcutQuery().apply {
	setQueryFlags(LauncherApps.ShortcutQuery.FLAG_MATCH_DYNAMIC or LauncherApps.ShortcutQuery.FLAG_MATCH_MANIFEST)
})
```

When running from Shizuku started with root, the call will result in a crash:

```
11-09 00:14:12.617 30021 30021 E AndroidRuntime: Process: com.kieronquinn.app.taptap, PID: 30021
11-09 00:14:12.617 30021 30021 E AndroidRuntime: java.lang.SecurityException: Calling package name mismatch
11-09 00:14:12.617 30021 30021 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
11-09 00:14:12.617 30021 30021 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2409)
11-09 00:14:12.617 30021 30021 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2392)
11-09 00:14:12.617 30021 30021 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2334)
11-09 00:14:12.617 30021 30021 E AndroidRuntime:        at com.kieronquinn.app.taptap.shizuku.ITapTapShizukuService$Stub$Proxy.getShortcuts(ITapTapShizukuService.java:151)
```

When running from Shizuku started with ADB, the call will work fine and a list of shortcuts will be returned.

We can trace the crash back to [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/pm/LauncherAppsService.java;drc=master;l=377):

```java
void verifyCallingPackage(String callingPackage) {
	int packageUid = -1;
	try {
		packageUid = AppGlobals.getPackageManager().getPackageUid(callingPackage,
				PackageManager.MATCH_DIRECT_BOOT_AWARE
						| PackageManager.MATCH_DIRECT_BOOT_UNAWARE
						| PackageManager.MATCH_UNINSTALLED_PACKAGES,
				UserHandle.getUserId(getCallingUid()));
	} catch (RemoteException ignore) {
	}
	if (packageUid < 0) {
		Log.e(TAG, "Package not found: " + callingPackage);
	}
	if (packageUid != injectBinderCallingUid()) {
		throw new SecurityException("Calling package name mismatch");
	}
}

//...

int injectBinderCallingUid() {
	return getCallingUid();
}
```

Which as you can see is checking the calling UID against the one found for the package name. It's worth noting that passing "android" as the package name does not work here either, and there's no package name for root, so it will always fail with that.

Just for the sake of it you can also prove this in the shell:

When running as `shell`:

```
raven:/ $ service call launcherapps 13 s16 com.android.shell
Result: Parcel(
  0x00000000: fffffffc 00000067 00740041 00650074 '....g...A.t.t.e.'
  0x00000010: 0070006d 00200074 006f0074 00690020 'm.p.t. .t.o. .i.'
  0x00000020: 0076006e 006b006f 00200065 00690076 'n.v.o.k.e. .v.i.'
  0x00000030: 00740072 00610075 0020006c 0065006d 'r.t.u.a.l. .m.e.'
  0x00000040: 00680074 0064006f 00270020 006e0069 't.h.o.d. .'.i.n.'
  0x00000050: 00200074 006e0061 00720064 0069006f 't. .a.n.d.r.o.i.'
  0x00000060: 002e0064 0073006f 0055002e 00650073 'd...o.s...U.s.e.'
  0x00000070: 00480072 006e0061 006c0064 002e0065 'r.H.a.n.d.l.e...'
  0x00000080: 00650067 00490074 00650064 0074006e 'g.e.t.I.d.e.n.t.'
  0x00000090: 00660069 00650069 00280072 00270029 'i.f.i.e.r.(.).'.'
```
(etc., it's passed the package name check that's what matters)

When running as `root`:

```
raven:/ # service call launcherapps 13 s16 com.android.shell
Result: Parcel(
  0x00000000: ffffffff 0000001d 00610043 006c006c '........C.a.l.l.'
  0x00000010: 006e0069 00200067 00610070 006b0063 'i.n.g. .p.a.c.k.'
  0x00000020: 00670061 00200065 0061006e 0065006d 'a.g.e. .n.a.m.e.'
  0x00000030: 006d0020 00730069 0061006d 00630074 ' .m.i.s.m.a.t.c.'
  0x00000040: 00000068 00000000                   'h.......        ')
```

My suggestion for getting around this would be to simply run the start command from the manager as `shell`, with `su -l 2000` - if that is possible with how Shizuku works (admittedly I've not checked). If possible, to maintain compatibility, it could also be an API option (hence making the issue here). 

If you need any more code, I can send a WIP version of Tap, Tap that has this issue.

Cheers

**Comment by KieronQuinn** [comment]
As a workaround, I've found out that if you do

```
init {
   Os.setuid(2000)
}
```

(at the top of the service)

It will work on root. Which I suppose is quite obvious now I think about it, as root is still able to do that. I still think this needs addressing though, as there is discrepancy between the two service start methods.

**Comment by RikkaW** [comment]
Talk about the conclusion first, using `setuid` in UserService is the correct and simplest way. There is nothing difference about the "start methods" since the change of the uid happens after the service is started.

-----

#### Something else

At first I misunderstood that you wanted the ability of using `Shizuku#transactRemote` with specific UID. This can be simplified as using binder in a same process, but as a different UID. In fact, this is also same from "use binder with a difference UID in UserService".

After discussing with others, we found it is not easy to achieve it. It is possible to change the UID at thread-level, but binder does not uses thread-level UID. The only solution maybe creating some sort of "process pool" and forward the binder call to those processes. This is similar to `Shizuku#transactRemote`, but `setuid` is called in those processes. There is a lot of work to do to implement it.

It may be true that if the user wants to use the binder with different UIDs. But I don't really want to implement such "process pool" , because this is complex but rarely used, and the user can simply solve the problem by starting different UserServices with different UIDs (use `setuid` in the service).

**Comment by KieronQuinn** [comment]
Makes sense - thanks!

I wasn't sure if `setuid` was safe given the docs say it's "not available to apps", but these aren't really apps and are root so I guess that just doesn't apply. Appreciate it being looked into, I was able to implement the proxying to access app shortcuts fine after doing `setuid` so I'm happy to have that as the solution.
