### ISSUE TITLE
加固之后app无法绑定服务

### ISSUE THREAD

**Issue by axb996** [RikkaApps/Shizuku-API#85]
如题，加固之后就无法绑定用户服务了，尝试反射未混淆加固的dex去绑定服务也不行，请问大佬有无解决方法(:

**Comment by vvb2060** [comment]
没有，加固后dex都没了，没通过环境检测不可能释放dex。我不认为app_process启动的进程会被任何加固认为是正常环境。
有能力的话，分离dex出来手动启动吧
