### ISSUE TITLE
shizuku是否可以集成在rom里？

### ISSUE THREAD

**Issue by Sailiy** [RikkaApps/Shizuku-API#87]
我可以提取安卓的system镜像，解压后，想把shizukuq加进去，实现开机自启动，
有没有具体的操作方法，还有就是如何解决selinux权限的问题，求解答？

**Comment by Hourmafia707** [comment]
https://github.com/RikkaApps/Shizuku-API/issues/87#issue-2243773939

**Comment by Hourmafia707** [comment]
https://github.com/Visnalize/win7-simu/issues/22#issue-1637219224

**Comment by Juniorseguin** [comment]
#109

**Comment by Juniorseguin** [comment]
#109

**Comment by Juniorseguin** [comment]
@Juniorseguin
