### ISSUE TITLE
更新了Service文件，但运行起来还是执行之前的代码逻辑

### ISSUE THREAD

**Issue by keluokeda** [RikkaApps/Shizuku-API#89]

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku-API?tab=readme-ov-file#userservice

> Be aware that, to let the service use the latest code, "Run/Debug configurations" - "Always install with package manager" in Android Studio should be checked.

检查一下（

**Comment by keluokeda** [comment]
<img width="1040" alt="image" src="https://github.com/RikkaApps/Shizuku-API/assets/16809185/3e7df1d4-4f5c-4cad-9f4b-1a88c8cc8185">
勾选后可以了；感谢。
